[workspace]

members = [
    "etl-core",
		"etl-mysql",
		"etl-sftp",
		"etl-aws-utils",
    "etl-job",
    "etl-grpc",
    "etl-dev-client-viewer",
    "etl-web",
    "mllp",
    "hl7-mllp-codec",
		#"etl-examples",
]

