//pub mod bytes_store;
/// Makes the events generated by observer available via grpc server
pub mod observer_server;
/// Wraps any simplestore and forwards the messages via a tokio channel
pub mod observer;
pub mod error;
/// For using the grpc service as a simple storage
pub mod client;


