credentials = "/home/yuri/.aws/credentials"
s3_bucket = "glue-source-pipeline-poc"
s3_keys = ["dev/synthea/AllergyIntolerance.ndjson"]
#s3_output_json = "dev/synthea/AllergyIntoleranceNdJson.txt"
#s3_output_csv = "dev/synthea/AllergyIntoleranceOutputCsv.txt"
host = "localhost"
port = "3306"
db_name = "IHDE_UDM"
user = "root"
pw = "admin"
max_connections = 2
#on_put_num_rows = 100
#on_put_num_rows_max = 150
