[package]
name = "etl-job"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
etl-core = { path = "../etl-core" }
serde_json = { version = "1.0" }
simple_logger = "2.1.0"
