[package]
name = "etl-dev-client-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
etl-core = { path = "../etl-core" }

log = "0.4"
simple_logger = "2.1.0"
